### PR TITLE
Remove sendgrid section tag generation

### PR DESCRIPTION
**Pull request by cilestin**
https://sendgrid.com/docs/for-developers/sending-email/section-tags/ have been deprecated. This removes their generation by the `render_skeleton` methods.

### CODE REVIEW

**Comment by cilestin** [comment]
Closing since we went a different direction and just modified things on the prism side instead.

**Comment by borisreitman** [comment]
Hello Drew,
I used to work at 500 Friends, which is why I'm receiving this
notification.  I'm interested to get back to work at 500 Friends. I
know it's was purchased by Merkle after I left, but I don't know who
is the product manager on your team. Can you connect me with him so
that I can talk to him directly? (Or is Hong still involved? I have
Hong's contacts).
Thanks,Boris Reitman
On 5/15/2020 at 5:35 PM, "Drew Fisher"  wrote:
	Closed #4.

**Comment by athtran** [comment]
I got this notification too. Hope you guys are doing well drew 😃

**Comment by rahulvij** [comment]
Don't break it Drew 😉

**Comment by cilestin** [comment]
@rahulvij don't tell me what to do!
@athtran thanks, you too!
@borisreitman I'll pass your request up the chain. Thanks for getting in touch :)

**Comment by ridiculous** [comment]
This is awesome

**Comment by borisreitman** [comment]
Drew, any updates on that?  If you can connect me with your HR, I can take it from there.

Thanks,
Boris

**Comment by cilestin** [comment]
Sorry @borisreitman, seems your request got lost in the shuffle at some point. Is the email stored in the repo still a good one to use to get in contact with you privately? I don't see an email listed on your github profile.

**Comment by borisreitman** [comment]
Hi Drew, 

You can contact me directly at boris.reitman@gmail.com

Thank you,
Boris

**Pull request closed without merging**
